# Generated by Django 4.2.4 on 2024-01-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_smth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smth',
            name='todo',
        ),
        migrations.AddField(
            model_name='smth',
            name='todo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
            preserve_default=False,
        ),
    ]
