# Generated by Django 4.2.4 on 2024-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_category_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
