# Generated by Django 4.2.4 on 2024-01-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_smth_todo_smth_todo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smth',
            old_name='todo_id',
            new_name='todo',
        ),
    ]
