# Generated by Django 4.2.4 on 2024-07-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.CreateModel(
            name='TodoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.todo')),
            ],
        ),
    ]
